# Main entrypoint of the workflow.
# Please follow the best practices:
# https://snakemake.readthedocs.io/en/stable/snakefiles/best_practices.html,
# in particular regarding the standardized folder structure mentioned there.

import pandas as pd
import yaml

# Import configuration files
params = yaml.load(open("config/params.yml", "r"), Loader=yaml.SafeLoader)
features = yaml.load(open("config/features.yml", "r"), Loader=yaml.SafeLoader)
samples = pd.read_table("config/samples.tsv", comment="#", dtype="str")


# Generate useful variables
SAMPLES = samples["sample"].drop_duplicates().values.tolist()
SAMPLE_LIB = samples[["sample", "library"]].values.tolist()
MAX_THREADS = params["max_threads"]
SNPEFF_DBS = features["snpeff"]["genome"]
BAM_REPORTS = ["stats.tsv", "flagstats.txt", "idxstats.tsv"]
PICARD_REPORTS = BAM_REPORTS + ["metrics.tsv"]
CHROMOSOMES = set(
    features["reference"]["autosomes"]
    + features["reference"]["male_chromosomes"]
    + features["reference"]["mitochondria"]
)


# Import subworkflows
include: "rules/folders.smk"
include: "rules/helpers/__main__.smk"
include: "rules/reads_functions.smk"
include: "rules/reads.smk"
include: "rules/reference.smk"
include: "rules/preprocess/__main__.smk"
include: "rules/align/__main__.smk"
include: "rules/genotype/__main__.smk"
include: "rules/snpeff.smk"
include: "rules/report/__main__.smk"


rule all:
    """Run the entire pipeline"""
    input:
        rules.report_step.input,
        rules.report_library.input,
        rules.report_chromosome.input,
