# Main entrypoint of the workflow.
# Please follow the best practices:
# https://snakemake.readthedocs.io/en/stable/snakefiles/best_practices.html,
# in particular regarding the standardized folder structure mentioned there.

import pandas as pd
import yaml

# Import configuration files
params = yaml.load(open("config/params.yml", "r"), Loader=yaml.SafeLoader)
features = yaml.load(open("config/features.yml", "r"), Loader=yaml.SafeLoader)
samples = pd.read_table("config/samples.tsv", comment="#", dtype="str")


# Generate useful variables
SAMPLES = samples["sample"].drop_duplicates().values.tolist()
SAMPLE_LIB = samples[["sample", "library"]].values.tolist()
MAX_THREADS = params["max_threads"]
SNPEFF_DBS = features["snpeff"]["genome"]
BAM_REPORTS = ["stats.tsv", "flagstats.txt", "idxstats.tsv"]
PICARD_REPORTS = BAM_REPORTS + ["metrics.tsv"]
CHROMOSOMES = set(
    features["reference"]["autosomes"]
    + features["reference"]["male_chromosomes"]
    + features["reference"]["mitochondria"]
)


# Import subworkflows
include: "rules/folders.smk"
include: "rules/sexy_functions.smk"
include: "rules/samtools.smk"
include: "rules/bcftools.smk"
include: "rules/reads_functions.smk"
include: "rules/reads.smk"
include: "rules/reference.smk"
include: "rules/fastqc.smk"
include: "rules/fastp_functions.smk"
include: "rules/fastp.smk"
include: "rules/bowtie2_functions.smk"
include: "rules/bowtie2.smk"
include: "rules/picard.smk"
include: "rules/swaps.smk"
include: "rules/gatk4_functions.smk"
include: "rules/gatk4.smk"
include: "rules/snpeff.smk"
include: "rules/report_library_functions.smk"
include: "rules/report_library.smk"
include: "rules/report_chromosome_functions.smk"
include: "rules/report_chromosome.smk"
include: "rules/report_step.smk"


rule all:
    """Run the entire pipeline"""
    input:
        # rules.reads_link.input,
        # rules.reads_fastqc.input,
        # rules.reference.input,
        # rules.fastp.input,
        # rules.bowtie2.input,
        # rules.picard.input,
        rules.swaps.input,
        # rules.gatk4_all.input,
        # rules.snpeff.input,
        rules.report_step.input,
        rules.report_library.input,
        rules.report_chromosome.input,
