READS = Path("results/reads/")
REFERENCE = Path("results/reference/")
FASTP = Path("results/fastp/")
BOWTIE2 = Path("results/bowtie2/")
PICARD = Path("results/picard/")
GATK = Path("results/gatk/")
SNPEFF = Path("results/snpeff/")
