READS = Path("results/reads/")
REFERENCE = Path("results/reference/")
FASTP = Path("results/fastp/")
BOWTIE2 = Path("results/bowtie2/")
PICARD = Path("results/picard/")
GATK = Path("results/gatk/")
SNPEFF = Path("results/snpeff/")

REPORTS_BY_SAMPLE = Path("reports/by_sample/")
REPORTS_BY_STEP = Path("reports/by_step/")
