reference:
    name: GRCg6a
    dna: resources/reference/ggal.mock.fa.gz
    gff: resources/reference/ggal.mock.gtf.gz  # Has to be a gff
    known_vcf: resources/reference/ggal.mock.vcf.gz  # or results/align/bcftools/bcftools.vcf.gz
    regions: resources/reference/ggal.mock.bed4
    autosomes: [1, 2]
    male_chromosomes: [Z]  # [X, Y]
    female_chromosomes: [Z,W]  # [X]
    mitochondria: [MT]
